language: ruby
rvm:
- 2.0.0-p648
- 2.1.8
- 2.2.4
- 2.3.0
sudo: required
dist: trusty
before_install: gem install bundler
addons:
  code_climate:
    repo_token:
      secure: "wJq+HdG1IyjHhuEkdAumXYWMHUFoyn78mTQYo+IeijxewfwORL/c1+jb2gXn5evj6/In+RDqoir8U8TgbuZa5Y5zuRDXeR/Y60OJi4yZRlA1NuHGZfbf/UkIJ9VFBxnPx2udjISGZDShnPMBV9zSrbFrcxYmvgBe/KENED9t3XVScEIthQE71zaJlellYAKAlGe6WxxxA2X7HSqa+OeCjLZb1ekgGspXd8xCFyOyjiWX5OBVmTxiP/RVWawtCrN8ak90Q0qRaufOAlk36I3BLW9EZkXB8Z873paet4g+rA/N0whEMLUUduxkTphThwF0HN4pibQMaf6BPqNdp1rrlXVt5FL8VymgwrFAvZBNW8vGhvMqIVe3Y44ynLVsrIiytEFTaJ28Xd7N8CVDQkurxXLVstk+kEHJLmZ8wDopbXxi0c9vDzHqSWsCr9Tai4Hkb8G/J4/o0NEsrw/BW9Xi0svbGN9kfJ9Id1+28w1vK0Qrobn+4JnEWHiJWndPNh9yLO1PhwCGbm3vl3d0KIIyFbA1a7vm6S8IxuZOFvEopSV2zWMbwh2teKOwdh2Kl9iJLQsoGIqldh7qaFa+GIQJbxSVqbQscb74silygVBBEgDqYVaoKtehd5NC9NAwnuVyzFwavFprPng0dod0uP37A1/vP+SzwRpeVSwR4ynCqhE="
