language: ruby
rvm:
- 2.0.0-p648
- 2.1.8
- 2.2.4
- 2.3.0
sudo: required
dist: trusty
before_install: gem install bundler
addons:
  code_climate:
    repo_token:
      secure: "BFKZ1wFZ3aSjn3N9wrtS5fKM0ge7O1udmMZO9oJh8Iqrq4WUPS1okfXbL1AgBoPJNN/2SlyuqRL/4rmkAKS/9IU08WPT8qz9WOnFo9CRyacnSrXZN78qbTEYh3LXgfIyEd3NxCXoyP5KdHheR2ZBlbFgFxvKr2GAIkSedAi0b8yJTDRz55NeDRVKhXv6yNEpHHfpXL9GDy73FV4SX07PW6i1GjIwEPGcWj1Iv8F8E6b3JFSiIK62hu+5tI7mpmUNDG3WeCWJ8BAxVfFNeT+b8E94B9iv2UYJLSN5DUuR+q3+aTJfapNdu7FIv7JkH0kC9Y2J2uiqb8q3DeZF7Ov0X1//s2LYnE13wAr2lOSj9fSkVQTXc5n9QgTclLoY8ogXq3WOhcFbXsyTgrYqKEG60AHXpFt6MHNOpf/bW5sfGmPOnoGRH1qF+LdphTaYihDz21wT5OdD6nAxdUN0AZ9P5HxFHtUhu0QygtK5qsEHUD5Pov/QEuqkQ141Rf8I++/fPgfu2LBsD4p74iKv2v1q5pGMXJQpJrLdJBPmTQKuWFMKPkTfy62nUOJqyYs5Ak80Ym2L2mydOFIThd4r4gwDAB+Xqclc+fdR9D43DWmvI6Py2jzNSrAJuGyDpmtUS6azYdXLMkoLaxs8QfWcxt8/TJgcmM4FqAtV80jtIzrwmgQ="
