version: "{build}"

clone_depth: 1

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet
  - bundler --version
  - bundle install --without development

build: off

test_script:
  - bundle exec rake

environment:
  matrix:
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
